// Copyright © 2021 CCP ehf.

#include "StdAfx.h"

// Blue interfaces
BLUE_DEFINE_INTERFACE_EXPORT( IBlueOS );
BLUE_DEFINE_INTERFACE_EXPORT( IBlueCallbackMan );
BLUE_DEFINE_INTERFACE_EXPORT( IBluePaths );
BLUE_DEFINE_INTERFACE_EXPORT( IMotherLode );
BLUE_DEFINE_INTERFACE_EXPORT( ICacheable );

// Python stuff
BLUE_DEFINE_INTERFACE_EXPORT( IBluePyOS );

// Blue persist mechanism
BLUE_DEFINE_INTERFACE_EXPORT( IBlueStream );
BLUE_DEFINE_INTERFACE_EXPORT( IResFile );
BLUE_DEFINE_INTERFACE_EXPORT( ITaskletTimer );
BLUE_DEFINE_INTERFACE_EXPORT( IBlueResMan );
BLUE_DEFINE_INTERFACE_EXPORT( IBlueResource );
BLUE_DEFINE_INTERFACE_EXPORT( IBlueMemStream );

BLUE_DEFINE_INTERFACE_EXPORT( IBlueObjectRecycler );
BLUE_DEFINE_INTERFACE_EXPORT( ICcpStatisticsAccumulator );

BLUE_DEFINE_INTERFACE_EXPORT( IUnloadable );