# Required metadata
sonar.projectKey=com.ccpgames:trinity
sonar.projectName=Trinity
sonar.projectVersion=0.0

# Comma-separated paths to directories with sources (required)
sonar.sources=.

# Language
sonar.language=c++

# Optional comma-separated list of additional libraries folders (such as /usr/include)
# sonar.cfamily.library.directories=lib

# Optional specific predefined macros
# sonar.cfamily.predefinedMacros=#define MY_MACRO(a) ((a)+1),#define DEBUG

sonar.cxx.cppcheck.path=C:\Program Files (x86)\Cppcheck\cppcheck.exe
sonar.cxx.cppcheck.reportPath=trinity_report.xml

# Encoding of the source files
sonar.sourceEncoding=UTF-8