// Copyright © 2014 CCP ehf.

/*****************************************************************
 * Standin file - autogenerated files are just made by the build 
 * server.
 * Do whatever you want!
 *****************************************************************/
#define EVEVER  9
#define EVEDELIVERY  9
#define EVEBUILD  9
#define EVEPROJECTVER 9
#define EVEVERSIONSTRING "9.9.9.9\0"
#define EVEBUILDDATE "Sometime, someday, somewhere\0"
#define EVECOMPANY "CCP hf.\0"
#define EVECOPYRIGHT "© 2009 CCP hf. All rights reserved.\0"
#define EVEPRODUCTVER "9.9\0"
#define EVEBRANCH "local\0"
#define EVECHANGELIST "0-perforce\0"
/* end */
